commands:
  - '[PLAYER] gamemode creative'
  - '[PLAYER] give %player_name% minecraft:diamond_axe 3'
  - '[CONSOLE] say AquaCount - Finally'
  - '[MESSAGE] &cDADADADADA'
  - '[MESSAGE] &#2E9CEDDSADASDAD'
  - '[SOUND] ENTITY_PLAYER_LEVELUP'

display:
  start_title: "&#2E9CED&lA&#30A5EF&lq&#32AFF2&lu&#33B8F4&la&#35C2F6&lC&#37CBF8&lo&#39D4FB&lu&#3ADEFD&ln&#3CE7FF&lt"
  start_subtitle: "&#2E9CED⌚ &fCounter started &e%aquacount_time_total%"
  stop_title: "&#2E9CED&lA&#30A5EF&lq&#32AFF2&lu&#33B8F4&la&#35C2F6&lC&#37CBF8&lo&#39D4FB&lu&#3ADEFD&ln&#3CE7FF&lt"
  stop_subtitle: "&#FF2F2F⌚ &fThe counter &cstopped"

messages:
  reload: "&#2E9CED[⌚] &fThe config.yml was reloaded with your new settings"
  usage: "&#2E9CED[⌚] &fExecute &#2E9CED/aquacount start <time> <unit>-> s,m,h,d,w,mo"
  started: "&#2E9CED[⌚] &fA new counter was started &e%duration%%unit% &7(%aquacount_time_total%)"
  permission: "&#FF1515[⌚] &fYou do not have permissions to run this command"
  unknown: "&#FF9E29[⌚] &fInvalid command run &#2E9CED/aquacount help &fsee the commands"
  nothing: "&#FF2F2F[⌚] &fRight now there is no counter in function"
  stop: "&#FF2F2F[⌚] &fThe running counter has just been finalized"
  number: "&#FF2F2F[⌚] &fThe time you inserted was invalid &fin the command"
  invalid: "&#2E9CED[⌚] &fThese are the valid units: &#2E9CEDs (seconds), m (minutes), h (hours), d (days), w (weeks), mo (months)"