name: AquaCount
version: '${project.version}'
main: team.aquatic.studios.AquaCount
api-version: '1.20'

commands:
  aquacount:
    description: Inicia un contador.
    usage: /<command> start <tiempo> <unidad>