name: AquaCount
version: '${project.version}'
main: team.aquatic.studios.AquaCount
api-version: '1.20'

commands:
  aquacount:
    description: Command for counter
    usage: /<command> start <time> <unit>