commands:
  - '[PLAYER] gamemode creative'
  - '[PLAYER] give %player_name% minecraft:diamond_axe 3'
  - '[CONSOLE] say AquaCount - Finally'
  - '[MESSAGE] &cDADADADADA'
  - '[MESSAGE] &#2E9CEDDSADASDAD'
  - '[SOUND] ENTITY_PLAYER_LEVELUP'

display:
  start_title: "&#2E9CED&lA&#30A5EF&lq&#32AFF2&lu&#33B8F4&la&#35C2F6&lC&#37CBF8&lo&#39D4FB&lu&#3ADEFD&ln&#3CE7FF&lt"
  start_subtitle: "&#2E9CED⌚ &fCounter started &e%aquacount_time_total%"
  stop_title: "&#2E9CED&lA&#30A5EF&lq&#32AFF2&lu&#33B8F4&la&#35C2F6&lC&#37CBF8&lo&#39D4FB&lu&#3ADEFD&ln&#3CE7FF&lt"
  stop_subtitle: "&#FF2F2F⌚ &fThe counter &cstopped"

messages:
  reload: "&#2E9CED[⌚] &fThe config.yml was reloaded with your new settings"
  usage: "&#2E9CED[⌚] &fExecute &#2E9CED/aquacount start <time> <unit>-> s,m,h,d,w,mo"
  started: "&#2E9CED[⌚] &aTimer is set statarted &a%duration% and %unit% %aquacount_time_total%"
  permission: "&#FF1515[⌚] &fYou do not have permissions to run this command"
  unknown: "&#FF9E29[⌚] &fInvalid command run &#2E9CED/aquacount help &fsee the commands"
  nothing: "&#FF2F2F[⌚] &fRight now there is no counter in function"
  stop: "&#FF2F2F[⌚] &#084CFBT&#1559FBi&#2166FBm&#2E73FBe&#3B7FFCr &#478CFCi&#5499FCs &#61A6FCs&#6EB3FCt&#7AC0FCo&#87CCFDp&#94D9FDp&#A0E6FDe&#ADF3FDd"
  number: "&#FF2F2F[⌚] &fThe time you inserted was &cinvalid &fin the command"
  invalid: "&#2E9CED[⌚] &fThese are the valid units: &#2E9CEDs (seconds), m (minutes), h (hours), d (days), w (weeks), mo (months)"